# Site settings
title: IncompletePackets
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://incpac.github.io" # the base hostname & protocol for your site
twitter_username: hideousnitrogen
github_username:  incomplatepackets

# Build settings
markdown: kramdown

gems:
  - therubyracer

include: ["_pages"]
